### ISSUE TITLE
画像の高さが上手く伸縮されないCSS上の問題

### ISSUE THREAD

**Issue by tokiwoousaka** [tokiwoousaka/takahashi#9]
親divの高さを正しく指定した上で

``` css
height: 90%;
width: auto; //あっても無くても表示かわんないっぽい
```

に効果なし。
想定より大きく表示されdivからはみ出して表示される。

なお、幅基準での伸縮はこの方法で問題なく表示されているもよう。

**Comment by tokiwoousaka** [comment]
CSSのオプション`scale`が関係？

**Comment by tokiwoousaka** [comment]
再現スライド

http://tokiwoousaka.github.io/takahashi/contents/Bug01.html

１ページ目が再現

２ページ目は苦肉の策（横長の画像を用意して幅で伸縮）

**Comment by tokiwoousaka** [comment]
https://twitter.com/trinity_site/status/593457918160154624

Heightを%指定しているのが原因？仕様ありとは？
pxでは意図したスライドには出来ないため単位の切り替えでは対応できないものの、有力な情報。

**Comment by NobukazuHanada** [comment]
んー?
たとえば

```
  height : 70%; 
```

とかにすればこれ、解決しない?
ちょっと意図がまだ良くわからないので。解決策かしらんけど。

**Comment by ncaq** [comment]
要素に合わせて自在に縮尺したいなら、画像はその要素のbackground-imageで指定する方が楽ですね

**Comment by tokiwoousaka** [comment]
> NobukazuHanada

いあ、heightの値を小さくした所でブラウザサイズを一定より縮めると同様の崩れが発生するようです。
（大概試したと思うのですがちょっと記憶が古いので今日明日中には再検証します）

> ncaq

うーん、コンテンツなのでとか、今後背景画像の設定を追加する可能性も否定できないとかの理由で、できるだけimageタグで解決したいですが・・・やはりそれしか無いんですかね・・。

**Comment by NobukazuHanada** [comment]
実は崩れが再現できてないので、なんとも.....

osxのchromeだからなのか...?

**Comment by tokiwoousaka** [comment]
んー、こっちもUbuntuのChoromiumなので表示は同じになっていると思うんだよなぁ・・・
画像を縦方向に縮めた時に画像と下divの比率が維持できなくなるのです。
![screenshot from 2015-10-08 22 24 03](https://cloud.githubusercontent.com/assets/2379085/10367423/629af3cc-6e0b-11e5-9fb8-946a907a3f6e.png)

**Comment by stefafafan** [comment]
いろいろググってわかったこと：
- `width` をパーセント指定で使う場合はよさそう :ok_woman: 
- `height` をパーセント指定で使うときは親要素をピクセルで指定しない限りへんなことになる（親の高さというより要素自体のサイズに依存？）、ので :no_good: 
- `vh` という単位を使えば画面の高さの割合で `height` を指定できるのでちょっと違うけどこれを使うのはどうか（提案）

こういうHTMLの場合、

``` html
<div id="parent">
  <div id="child1">
    <div id="child2">
    </div>
  </div>
</div>
```

こうではなく

``` css
#parent
{
  height: 50%;
}
#child1
{
  height: 100%;
}
#child2
{
  height: 90%;
}
```

こんな感じ

``` css
#parent
{
  height: 50vh;
}
#child1
{
  height: 50vh; /* 親の100%の高さ、つまりvhだと同じ */
}
#child2
{
  height: 45vh; /* 親の90%の高さ、つまり50vhの90%の45vh */
}
```
